- .eslintrc.json
- package.json
- src/config.js
- test/before-tests.js
- test/unit/config.spec.js
closes https://github.com/dorbel-tech/dorbel-shared/issues/2
> config values will be put into process.env

- .eslintrc.json
- package.json
- src/utils/waitForConnection.js
> adding port support to waitForConnection

- package.json
- src/utils/userManagement.js
- yarn.lock
closes #20 
closes https://github.com/dorbel-tech/dorbel-app/issues/58
> Adding Redis caching of auth0 user detail and token.

- package.json
- scripts/release.sh
- src/logger.js
- yarn.lock
closes https://github.com/dorbel-tech/dorbel-app/issues/113
> Added SumoLogic logs integration

- package.json
- src/logger.js
> Write application name to log

- package.json
- src/koa-middleware/request-logger.js
- src/utils/userManagement.js
- test/before-tests.js
- test/unit/logger.spec.js
- test/unit/userManagement.spec.js
- yarn.lock
closes https://github.com/dorbel-tech/dorbel-app/issues/375
closes https://github.com/dorbel-tech/dorbel-shared/issues/41
> old user token bug 

- src/koa-middleware/request-logger.js
- src/utils/generic.js
1. Remove health checks from request log
2. Don't remove zero from phone dorbel-tech/dorbel-app#433
> Multiple features

- package.json
- src/koa-middleware/error-handler.js
- src/utils/sentryReporter.js
- yarn.lock
closes https://github.com/dorbel-tech/dorbel-app/issues/341
> integrate sentry.io

- src/utils/userManagement.js
Needed for https://github.com/dorbel-tech/dorbel-app/issues/365
> separating get-profile-from-token to it's own function

- package.json
- src/index.js
- src/koa-middleware/error-handler.js
- src/utils/newrelic.js
- src/utils/serverRunner.js
- test/unit/serverRunner.spec.js
> Report error call-stack to New Relic 

- src/utils/messageBus.js
Adding for dorbel-tech/dorbel-app#575
connects to  dorbel-tech/dorbel-app#572
> Auto adding _listing_url to message

- src/utils/generic.js
connects to https://github.com/dorbel-tech/dorbel-app/issues/552
> Add normalize slug generic function

- .codecov.yml
- .gitignore
- README.md
- package.json
- yarn.lock
> Add unit test coverage support

- .gitignore
- package.json
- src/utils/userManagement.js
- yarn.lock
Remove auth0 ManagementClient (singleton) lazy loading completely to prevent old token to be used as we must refresh the token every 24h.
closes dorbel-tech/dorbel-app#619
> Fixing user detail update issue. 

- package.json
- src/index.js
- src/utils/domainErrors.js
connects to https://github.com/dorbel-tech/dorbel-app/issues/698
> Move domainErrors.js from oheApi to dorbel-shared

- src/helpers/headers.js
- src/index.js
connects to https://github.com/dorbel-tech/dorbel-app/issues/414
> Adding cache control headers helper

- src/utils/userManagement.js
* add tenant_profile to publicProfile 
* renamed facebook_link to facebook_url for consistency (will update front-gateway too)
* fallback to FB login only if tenant profile not set
**only merge when front gateway PR is approved**
connects to https://github.com/dorbel-tech/dorbel-app/issues/782
> add tenant_profile to publicProfile

- src/utils/userManagement.js
required for https://github.com/dorbel-tech/dorbel-app/pull/948
> get public profile by email

- src/utils/userManagement.js
needed for https://github.com/dorbel-tech/dorbel-app/pull/948
> add user id to public profile

- src/utils/generic.js
- src/utils/messageBus.js
- src/utils/segment.js
1. Fixing listing_url to property url for intercom. connects to https://github.com/dorbel-tech/dorbel-app/issues/1164
2. Remove OHE_FOLLOW event types. connects to https://github.com/dorbel-tech/dorbel-app/issues/1031
> Fixing listing_url to property url for intercom

- package.json
- src/utils/segment.js
Connects to https://github.com/dorbel-tech/dorbel-app/issues/1157
> Add user_metadata settings as segment traits

- src/koa-middleware/request-logger.js
- test/middleware/request-logger.spec.js
> Added IP address to logger

- src/koa-middleware/error-handler.js
- test/unit/middleware/error-handler.spec.js
closes https://github.com/dorbel-tech/dorbel-app/issues/1312
> Better Sequelize error logging

- package.json
- yarn.lock
relates to https://github.com/dorbel-tech/dorbel-app/pull/1399
> upgrading new relic

- src/koa-middleware/swagger-model-validator.js
connects to https://github.com/dorbel-tech/dorbel-app/issues/1387
> supporting new fleek context structure

- src/utils/user/helpers.js
connects to https://github.com/dorbel-tech/dorbel-app/issues/1493
> Adding workplace to tenant profile if exists from Facebook 

- src/utils/user/helpers.js
Following the changes here: https://github.com/dorbel-tech/dorbel-app/pull/1605
> Syncing user profile with front-gateway
